language: python
python:
    - 3.5
before_script:
    - pip install --upgrade pip
    - pip install cython numpy nose pandas
    - python setup.py build_ext --inplace install
    - pip install hdbscan
script: 
    - nosetests

