version: 2.1

jobs:
    build:
        docker:
            - image: python:3.6
        steps:
            - checkout
            - run: |
                python3.6 -m venv venv
                source ./venv/bin/activate
                pip install numpy cython h5py
                python setup.py build_ext --inplace install
                pip install nose tqdm joblib 
                python mp.py
                mkdir log
                nosetests --with-xunit --xunit-file=log/nosetests.xml
            - store_test_results:
                path: log


