version: 2.1

jobs:
    build:
        docker:
            - image: python:3.6
        steps:
            - checkout
            - run: |
                pip install numpy cython h5py
                pip install nose tqdm joblib                 
                python setup.py build_ext
                python mp.py
                mkdir log
                nosetests --with-xunit --xunit-file=log/nosetests.xml
            - store_test_results:
                path: log


