version: 2.1

jobs:
    build:
        docker:
            - image: python:3.6
        parallelism: 4
        steps:
            - checkout
            - run: |
                python3.6 -m venv venv
                source ./venv/bin/activate
                pip install numpy cython
                python setup.py build_ext --inplace install
                pip install nose
                python multiprocessing.py
                mkdir log
                nosetests --with-xunit --xunit-file=log/nosetests.xml
            - store_test_results:
                path: log


