version: 2.1
jobs:
    build:
        docker:
            - image: circleci/python:3.6
        steps:
            - checkout
            - run: |
                python3.6 -m venv venv
                source ./venv/bin/activate
                pip install numpy cython
                python setup.py build_ext --inplace install
                pip install nose
                mkdir log
                nosetests --with-xunit --xunit-file=log/nosetests.xml
            - store_test_results:
                path: log
